app/blueprints/authentication/models.py
from app import db, login
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)
    created_on = db.Column(db.DateTime, default=datetime.utcnow)

    def hash_pass(self, original_password):
        self.password = generate_password_hash(original_password)

    def check_password(self, original_password):
        return check_password_hash(self.password, original_password)

    def __repr__(self):
        return f"<user: {self.first_name} {self.last_name}>"
    
@login.user_loader
def login_user(id):
    return User.query.get(int(id))

app/blueprints/movies/models.py
from app import db

class Rating(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    movie = db.Column(db.String)
    thumbs_up = db.Column(db.Boolean, default=False)
    thumbs_down = db.Column(db.Boolean, default=False)

app/blueprints/authentication/forms.py
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import Email, EqualTo, email_validator
from flask_wtf import FlaskForm

class Register(FlaskForm):
    first_name = StringField()
    last_name = StringField()
    email = StringField(validators=[Email(message='Not a valid email address')])
    password = PasswordField()
    confirm_password = PasswordField(EqualTo('password'))
    submit = SubmitField('Register')

class Login(FlaskForm):
    email = StringField(validators=[Email(message='Not a valid email address')])
    password = PasswordField()
    submit = SubmitField('Login')

app/blueprints/movies/forms.py
from wtforms import StringField, SubmitField
from flask_wtf import FlaskForm

class Search_Movie(FlaskForm):
    name = StringField()
    submit = SubmitField('search')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
moment = Moment()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)

    login.init_app(app)
    login.login_view = 'authentication.login'
    login.login_message_category = 'warning'

    with app.app_context():
        from app.blueprints.main import bp as main
        app.register_blueprint(main)

        from app.blueprints.authentication import bp as authentication
        app.register_blueprint(authentication)

        from app.blueprints.movies import bp as movies
        app.register_blueprint(movies)

        from .import routes, models

    return app

app/blueprints/authentication/__init__.py
from flask import Blueprint

bp = Blueprint('authentication' ,__name__, url_prefix='/')

from .import models, routes

app/blueprints/authentication/routes.py
from .import bp as authentication
from app import db
from flask import current_app as app, render_template, request, redirect, url_for, flash, session
from flask_login import login_user, current_user, login_required, logout_user
from .forms import Register, Login
from .models import User

@authentication.route('/register', methods=['GET', 'POST'])
def register():
    form = Register()

    if form.validate_on_submit():
        data = {
            'first_name' : request.form.get('first_name'),
            'last_name' : request.form.get('last_name'),
            'email' : request.form.get('email'),
            'password' : request.form.get('password')
        }
        u = User(first_name=data['first_name'], last_name=data['last_name'], email=data['email'], password=data['password'])

        u.hash_pass(u.password)

        db.session.add(u)
        db.session.commit()

        flash("You have successfully registered!", 'primary')

        return redirect(url_for('authentication.login'))

    content = {
        'form' : form
    }

    return render_template('register.html', **content)

@authentication.route('/login', methods=['GET', 'POST'])
def login():
    form = Login()
    
    user = User.query.filter_by(email=request.form.get('email')).first()
    if form.validate_on_submit():
        if user is None or not user.check_password(request.form.get('password')):
            flash("You have entered incorrect details, please try again", 'danger')
            return redirect(url_for('authentication.login'))
        login_user(user)
        flash("You have successfully logged in!", 'success')
        return redirect(url_for('main.index'))
    content = {
        'form' : form
    }
    return render_template('login.html', **content)

@authentication.route('logout')
def logout():
    logout_user()
    flash("You have successfully logged out!", 'info')
    return redirect(url_for('authentication.login'))

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from .import models, routes

app/blueprints/main/routes.py
from .import bp as main
from flask import current_app as app, render_template

@main.route('/')
def index():
    return render_template('index.html')

    

app/blueprints/movies/__init__.py
from flask import Blueprint

bp = Blueprint('movies', __name__, url_prefix='/')

from .import models, routes

app/blueprints/movies/routes.py
from .import bp as movies
import requests 
from flask import current_app as app, render_template, request, redirect, url_for, flash, session
from app import db
from flask_login import login_required, current_user
from .forms import Search_Movie
from .models import Rating

@movies.route('/search', methods=['GET', 'POST'])
def search():
    form = Search_Movie()
    movies = []

    if form.validate_on_submit():
        data = {
            'movie' : request.form.get('name')
        }

        search = f"https://api.themoviedb.org/3/search/movie?api_key=230fd3a192d8580ee857e1e9bd72d2a1&query={data['movie']}"
        response = requests.request("GET", search)
        r = response.json()
        for _ in r['results']:
            movies.append(_)
        
    content = {
        'movies' : movies,
        'form' : form
    }
    return render_template('search.html', **content)


@movies.route('/down', methods=['GET', 'POST'])
def Rate_up():
    print('somethings happening')
    movie = request.args.get('name')
    r = Rating(movie=movie, thumbs_up=True)
    db.session.add(r)
    db.session.commit()
    return redirect(url_for('movies.Ratings'))

@movies.route('/up', methods=['GET', 'POST'])
def Rate_down():
    print('somethings happening')
    movie = request.args.get('name')
    r = Rating(movie=movie, thumbs_down=True)
    db.session.add(r)
    db.session.commit()
    return redirect(url_for('movies.Ratings'))

@movies.route('/ratings')
def Ratings():
    all_ratings = Rating.query.all()
    unique_titles = []
    data = []
    for _ in all_ratings:
        if _.movie not in unique_titles:
            unique_titles.append(_.movie)
    for title in unique_titles:
        count_up = 0
        count_down = 0
        for rating in all_ratings:
            if title == rating.movie:
                if rating.thumbs_up == True:
                    count_up += 1
                else: count_down += 1
        data.append((title, count_up, count_down))
    print(data)
    return render_template('ratings.html', data=data)

@movies.route('/rate-me')
def single_movie():
    _id = int(request.args.get('id'))
    search = f'https://api.themoviedb.org/3/movie/{_id}?api_key=230fd3a192d8580ee857e1e9bd72d2a1&language=en-US'
    response = requests.request("GET", search)
    m = response.json()
    return render_template('movie.html', movie=m)

app/templates/index.html
{% extends 'layout.html'%}

{% block title %}
{{ super() }} | Homepage
{% endblock %}

{% block content %}
<br>
<div>
<h3>
    Welcome to Nisarg Patel's Movie rating App!
</h3>
<p>This was developed as the coding challenge for Nisarg Patel's Year One Interview Application.</p> 
<p>This app is created using Flask, and the cloud based postgres database used is called ElephantSQL</p>
</div>

{% endblock %}

app/templates/layout.html
{% set navigation_bar = [
    ('/search', 'search', 'Search'),
    ('/ratings', 'ratings', 'Ratings'),
] -%}

{%  set active_page = active_page|default('index') -%}

<!doctype html>
<html lang="en">

<head>
    <title>
        {% block title %}
        Blockbuster-raters
        {% endblock %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

    <header>
        {% include './partials/navigation.html' %}
    </header>

    <main>
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for c, m in messages %}
            <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong> {{ m }} </strong>
            </div>
            {% endfor %}
            {% endif%}
            {% endwith %}


            {% block content%}
            {% endblock %}
        </div>
    </main>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
    {% endblock %}
</body>

</html>

app/templates/login.html
{% extends 'layout.html'%}

{% block title %}
    {{ super() }} | Login
{% endblock %}

{% block content %}
<h3>
    Login to your account below!
</h3>
<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('authentication.login') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.email(class='form-control', placeholder='Email') }}
                {%for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{error}}</strong>
                </div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password(class='form-control', placeholder='Password') }}
            </div>
            {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <a href="{{url_for('authentication.register') }}">Not registered? Click Here!</a>
    </div>
</div>
{% endblock %}

app/templates/movie.html
{% extends 'layout.html'%}

{% block title %}
    {{ super() }} | {{movie.original_title}}
{% endblock %}

{% block content %}


<div class="card" style="width: 18rem;">
    <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2/{{movie.poster_path}}" class="card-img-top" alt="{{movie.original_title}} poster path">
    <div class="card-body">
        <h5 class="card-title">{{movie.original_title}}</h5>
        <p class="card-text">{{movie.overview}}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{movie.release_date}}</li>
    </ul>
    <div class="card-body">
        <a href="{{url_for('movies.Rate_up', name=movie.original_title)}}" class="card-link" method='POST'><i class="fa fa-thumbs-up"></i></a>
        <a href="{{url_for('movies.Rate_down', name=movie.original_title)}}" class="card-link" method='POST'><i class="fa fa-thumbs-down"></i></a>
    </div>
</div>

{% endblock %}

app/templates/partials/navigation.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Blockbuster-rater</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% for href, id, caption in navigation_bar %}
                <li class="nav-item {% if id==active_page %}active{% endif %} ">
                    <a class="nav-link" href="{{ href|e }}">{{ caption|e }}<span class="sr-only">(current)</span></a>
                </li>
            {% endfor %}
        </ul>
        <ul class="navbar-nav m1-auto">
            {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{url_for('authentication.login')}}" class="nav-link">Login</a></li>
                <li class="nav-item">
                    <a href="{{url_for('authentication.register')}}" class="nav-link">Register</a></li>
            {% else %}
                <li class="nav-item">
                    <a href="{{url_for('authentication.logout')}}" class="nav-link">Logout</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

app/templates/ratings.html
{% extends 'layout.html'%}
{% set active_page='Rating'-%}

{% block title %}
{{ super() }} | Ratings
{% endblock %}

{% block content %}


<table class="table table-striped">
    <thead class='thread-dark'> 
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Thumbs Up</th>
            <th scope="col">Thumbs Down</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in data %}
        <tr>
            <td>{{movie[0]}} </td>
            <td>{{movie[1]}}</td>
            <td>{{movie[2]}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/register.html
{% extends 'layout.html'%}

{% block title %}
    {{ super() }} | Register
{% endblock %}

{% block content %}
<h3>
    Welcome to the Blockbuster-Rater!! Register your account below!
</h3>

<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('authentication.register') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.first_name(class='form-control', placeholder='first_name') }}
            </div>
            <div class="form-group">
                {{ form.last_name(class='form-control', placeholder='last_name') }}
            </div>
            <div class="form-group">
                {{ form.email(class='form-control', placeholder='Email') }}
                {%for error in form.email.errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{error}}</strong>
                    </div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password(class='form-control', placeholder='Password') }}
            </div>
            <div class="form-group">
                {{ form.confirm_password(class='form-control', placeholder='Confirm Password') }}
            </div>
            {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/search.html
{% extends 'layout.html'%}
{% set active_page='search'-%}

{% block title %}
    {{ super() }} | Search
{% endblock %}

{% block content %} 
<br>
<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('movies.search') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.name(class='form-control', placeholder='Title of a Movie to search for') }}
            </div>
            {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>

<div class="card-deck">
    <div class="card" style='width:400px;'>
        <div class='card-header'>Your Results
            <ul class="list-group list-group-flush">
                {% if movies %}
                    {% for movie in movies %}
                     <li class="list-group-item"> 
                        <a href="{{url_for('movies.single_movie', id=movie.id)}}">{{ movie.original_title }}</a>
                     </li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item">No results to display</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}